Add: VBA print format for XOR shellcode runner
chvancooten/OSEP-Code-Snippets pull request #8
Opened 2023-12-27 21:10 UTC by A1vinSmith

2023-12-28 10:06 UTC, chvancooten requested changes
The file `program.cs` is placed in the root directory, please move (and merge) it with the existing `program.cs`. To prevent removing/overriding existing functionality, please add a switch to the program to change the output format on the command line (default to C#).

2024-01-03 21:51 UTC, A1vinSmith commented
Thanks @chvancooten, I've updated the file. It prints out the C# payload by default. And VBA by using a switch `-VBA`

2024-01-04 15:16 UTC, chvancooten approved these changes

2024-01-04 15:17 UTC, merged

2024-01-04 15:17 UTC, chvancooten commented
Thanks @A1vinSmith, I made some final adjustments and merged the PR :)